### ISSUE TITLE
Small errors in the docs

### ISSUE THREAD

**Issue by alexbrahastoll** [myfreecomm/billimatic-client-ruby#30]
Hi there,

We at Siinco are using the latest version of the gem (0.14.1) and we have noticed some mistakes in the documentation.

1) The documentation instructs one to search for a person using `client.people.search(cpf)`, however what actually works is `client.people.search(cpf: cpf)`:

```
2.4.1 :002 > client = Billimatic.client('4d34754cd68bbe74d725f6c8c9f6b48f')
#<Billimatic::Client:0x007fa3645264f8 @http=#<Billimatic::Http:0x007fa3645264d0 @token="4d34754cd68bbe74d725f6c8c9f6b48f">>
2.4.1 :003 > client.people.search('017.458.856-92')
ArgumentError: wrong number of arguments (given 1, expected 0)
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/billimatic-client-0.14.1/lib/billimatic/resources/person.rb:11:in `search'
	from (irb):3
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
2.4.1 :004 > client.people.search(cpf: '017.458.856-92')
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://sandbox.billimatic.com.br/api/v1/people/search?cpf=017.458.856-92 response_code=200 return_code=ok total_time=0.906926
/Users/alexbrahastoll/.rvm/gems/ruby-2.4.1/gems/awesome_print-1.7.0/lib/awesome_print/formatters/base_formatter.rb:31: warning: constant ::Fixnum is deprecated
[
    [0] {
                  :id => 1614,
          :account_id => 29,
                :name => "Joao (Cartão)",
                 :cpf => "01745885692",
               :email => nil,
             :zipcode => nil,
             :address => nil,
              :number => nil,
          :complement => nil,
            :district => nil,
                :city => nil,
               :state => nil,
            :comments => nil,
        :client_since => nil,
          :created_at => Tue, 15 Aug 2017 18:29:34 -0300
    }
]
2.4.1 :005 >
```

2) The documentation states that a PATCH request is made when updating a person (`client.people.update(billimatic_person_id, request_body)`), however the client is actually making a PUT request (not a big deal, however it does matter if one is writing HTTP stubs with WebMock for example).

Thanks!

**Comment by guilhermeFranco** [comment]
Fixed on #29
